/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HMI_Back */

#ifndef _Included_HMI_Back
#define _Included_HMI_Back
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HMI_Back
 * Method:    getCyclePercent
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_HMI_1Back_getCyclePercent
  (JNIEnv *, jobject, jint);

/*
 * Class:     HMI_Back
 * Method:    isRideRunning
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_HMI_1Back_isRideRunning
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     HMI_Back
 * Method:    isRow1Locked
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_HMI_1Back_isRow1Locked
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     HMI_Back
 * Method:    isRow2Locked
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_HMI_1Back_isRow2Locked
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     HMI_Back
 * Method:    isReadyToRun
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_HMI_1Back_isReadyToRun
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     HMI_Back
 * Method:    getErrorMessage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HMI_1Back_getErrorMessage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     HMI_Back
 * Method:    lockRestraints
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_HMI_1Back_lockRestraints
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     HMI_Back
 * Method:    unlockRestraints
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_HMI_1Back_unlockRestraints
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     HMI_Back
 * Method:    isRotationGondolaClockwise
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_HMI_1Back_isRotationGondolaClockwise
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     HMI_Back
 * Method:    isRotationGondolaCounterClockwise
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_HMI_1Back_isRotationGondolaCounterClockwise
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     HMI_Back
 * Method:    isRotationArmClockwise
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_HMI_1Back_isRotationArmClockwise
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     HMI_Back
 * Method:    isRotationArmCounterClockwise
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_HMI_1Back_isRotationArmCounterClockwise
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
